export const GET_USER_DATA_PEDDING = "GET_USER_DATA_PEDDING";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR";
export const REMOVE_USER = "REMOVE_USER";
export const SET_USER_DATA = "SET_USER_DATA";